//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class AuditSearch: ICloneable
    {
    	public AuditSearch () {}
    
    	#region ICloneable Members
        public AuditSearch Clone()
        {
            return (AuditSearch)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (AuditSearch)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public string content { get; set; }
    }
}
