
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MASTERPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class Concept_KeyPhrase: ICloneable
{
	public Concept_KeyPhrase () {}

	#region ICloneable Members
    public Concept_KeyPhrase Clone()
    {
        return (Concept_KeyPhrase)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (Concept_KeyPhrase)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public Nullable<int> ConceptID { get; set; }

    public Nullable<int> KeyPhraseID { get; set; }

    public Nullable<int> LawID { get; set; }

    public Nullable<int> Count { get; set; }

}

}
