
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MASTERPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class ConceptMapping: ICloneable
{
	public ConceptMapping () {}

	#region ICloneable Members
    public ConceptMapping Clone()
    {
        return (ConceptMapping)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (ConceptMapping)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public Nullable<int> ConceptID { get; set; }

    public Nullable<int> ArticalID { get; set; }

    public Nullable<int> ChapterID { get; set; }

    public Nullable<int> ChapterItemID { get; set; }

    public Nullable<int> ClaustID { get; set; }

    public Nullable<int> PointID { get; set; }

    public Nullable<int> LawID { get; set; }

    public Nullable<int> KeyPhraseID { get; set; }

}

}
