
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MASTERPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class Concept: ICloneable
{
	public Concept () {}

	#region ICloneable Members
    public Concept Clone()
    {
        return (Concept)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (Concept)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

}

}
