//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_MENU: ICloneable
    {
    	public DATA_MENU () {}
    
    	#region ICloneable Members
        public DATA_MENU Clone()
        {
            return (DATA_MENU)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_MENU)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string PageID { get; set; }
        public string UrlPath { get; set; }
        public Nullable<double> OrderIdx { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<bool> DelFlg { get; set; }
        public string Roles { get; set; }
    }
}
