//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Data_Luat_HTML: ICloneable
    {
    	public Data_Luat_HTML () {}
    
    	#region ICloneable Members
        public Data_Luat_HTML Clone()
        {
            return (Data_Luat_HTML)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (Data_Luat_HTML)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public Nullable<int> LawID { get; set; }
        public string ContentHTML { get; set; }
    }
}
