
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MASTERPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class DATA_2_Chuong: ICloneable
{
	public DATA_2_Chuong () {}

	#region ICloneable Members
    public DATA_2_Chuong Clone()
    {
        return (DATA_2_Chuong)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (DATA_2_Chuong)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public Nullable<int> Index { get; set; }

    public Nullable<int> LuatID { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

}

}
