//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_CRAWL: ICloneable
    {
    	public DATA_CRAWL () {}
    
    	#region ICloneable Members
        public DATA_CRAWL Clone()
        {
            return (DATA_CRAWL)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_CRAWL)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public string TenCauHoi { get; set; }
        public string LinhVuc { get; set; }
        public string NoiDungCauHoi { get; set; }
        public string CauTraLoi { get; set; }
        public string Luat { get; set; }
        public string KeyWords { get; set; }
    }
}
