//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_REWARD: ICloneable
    {
    	public DATA_REWARD () {}
    
    	#region ICloneable Members
        public DATA_REWARD Clone()
        {
            return (DATA_REWARD)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_REWARD)this.MemberwiseClone();
        }
        #endregion
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> PeriodID { get; set; }
        public string UnitID { get; set; }
        public string UnitParentID { get; set; }
        public string Code { get; set; }
        public string Reason { get; set; }
        public Nullable<long> Birthday { get; set; }
        public string TikiCode { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> OCRAt { get; set; }
        public string OCRBy { get; set; }
        public string Note { get; set; }
        public string RejectNote { get; set; }
        public Nullable<bool> RejectFlg { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> SendAt { get; set; }
        public string SendBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> ApproveAt { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<bool> DelFlg { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> OwnerFlg { get; set; }
        public Nullable<short> StatusSign { get; set; }
    }
}
