//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_1_Luat: ICloneable
    {
    	public DATA_1_Luat () {}
    
    	#region ICloneable Members
        public DATA_1_Luat Clone()
        {
            return (DATA_1_Luat)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_1_Luat)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public Nullable<int> Index { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string ContentHTML { get; set; }
        public string LawNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TotalChapter { get; set; }
        public string LawDate { get; set; }
    }
}
