//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class DATA_4_Dieu: ICloneable
    {
    	public DATA_4_Dieu () {}
    
    	#region ICloneable Members
        public DATA_4_Dieu Clone()
        {
            return (DATA_4_Dieu)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (DATA_4_Dieu)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> LuatID { get; set; }
        public Nullable<int> ChuongID { get; set; }
        public Nullable<int> MucID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}
