//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class KeyPhrase_Title_Mapping: ICloneable
    {
    	public KeyPhrase_Title_Mapping () {}
    
    	#region ICloneable Members
        public KeyPhrase_Title_Mapping Clone()
        {
            return (KeyPhrase_Title_Mapping)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (KeyPhrase_Title_Mapping)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public Nullable<int> KeyPhraseID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> ChapterItemID { get; set; }
        public Nullable<int> ArticalID { get; set; }
        public Nullable<int> LawID { get; set; }
    }
}
