//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MASTERPMEntities : DbContext
    {
        public MASTERPMEntities()
            : base("name=MASTERPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD_AUTONUMBER> AD_AUTONUMBER { get; set; }
        public virtual DbSet<AD_CONFIG> AD_CONFIG { get; set; }
        public virtual DbSet<AD_CONTROL> AD_CONTROL { get; set; }
        public virtual DbSet<AD_LOG> AD_LOG { get; set; }
        public virtual DbSet<AD_PAGE> AD_PAGE { get; set; }
        public virtual DbSet<AD_ROLE> AD_ROLE { get; set; }
        public virtual DbSet<AD_ROLE_PAGE> AD_ROLE_PAGE { get; set; }
        public virtual DbSet<AD_USER> AD_USER { get; set; }
        public virtual DbSet<AuditSearch> AuditSearch { get; set; }
        public virtual DbSet<Concept> Concept { get; set; }
        public virtual DbSet<ConceptMapping> ConceptMapping { get; set; }
        public virtual DbSet<DATA_1_Luat> DATA_1_Luat { get; set; }
        public virtual DbSet<DATA_2_Chuong> DATA_2_Chuong { get; set; }
        public virtual DbSet<DATA_3_Muc> DATA_3_Muc { get; set; }
        public virtual DbSet<DATA_4_Dieu> DATA_4_Dieu { get; set; }
        public virtual DbSet<DATA_5_Khoan> DATA_5_Khoan { get; set; }
        public virtual DbSet<DATA_6_Diem> DATA_6_Diem { get; set; }
        public virtual DbSet<DATA_ACCOUNT> DATA_ACCOUNT { get; set; }
        public virtual DbSet<DATA_CRAWL> DATA_CRAWL { get; set; }
        public virtual DbSet<DATA_MENU> DATA_MENU { get; set; }
        public virtual DbSet<DATA_REWARD> DATA_REWARD { get; set; }
        public virtual DbSet<KeyPhrase_Title_Mapping> KeyPhrase_Title_Mapping { get; set; }
        public virtual DbSet<KeyRelate> KeyRelate { get; set; }
        public virtual DbSet<M_COMMON> M_COMMON { get; set; }
        public virtual DbSet<M_UNIT> M_UNIT { get; set; }
        public virtual DbSet<query> query { get; set; }
        public virtual DbSet<QuestionContain> QuestionContain { get; set; }
        public virtual DbSet<QuestionType> QuestionType { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<USER_TOKEN> USER_TOKEN { get; set; }
        public virtual DbSet<Concept_KeyPhrase> Concept_KeyPhrase { get; set; }
        public virtual DbSet<KeyPhrase> KeyPhrase { get; set; }
        public virtual DbSet<KeyPhraseMapping> KeyPhraseMapping { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
