//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTERPM.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class user: ICloneable
    {
    	public user () {}
    
    	#region ICloneable Members
        public user Clone()
        {
            return (user)this.MemberwiseClone(); 
        }
    
        object ICloneable.Clone()
        {
            return (user)this.MemberwiseClone();
        }
        #endregion
        public int ID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> Type { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
    }
}
