
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MASTERPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class USER_TOKEN: ICloneable
{
	public USER_TOKEN () {}

	#region ICloneable Members
    public USER_TOKEN Clone()
    {
        return (USER_TOKEN)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (USER_TOKEN)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string Token { get; set; }

    public string Username { get; set; }

    public Nullable<System.Guid> AccountID { get; set; }

}

}
