
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class AD_CONTROL: ICloneable
{
	public AD_CONTROL () {}

	#region ICloneable Members
    public AD_CONTROL Clone()
    {
        return (AD_CONTROL)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (AD_CONTROL)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string ControlID { get; set; }

    public string PageID { get; set; }

    public string Name { get; set; }

    public string AbsoluteUrl { get; set; }

    public string MethodRequest { get; set; }

}

}
