
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class KeyPhrase: ICloneable
{
	public KeyPhrase () {}

	#region ICloneable Members
    public KeyPhrase Clone()
    {
        return (KeyPhrase)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (KeyPhrase)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string KeyPhrase1 { get; set; }

    public Nullable<int> source { get; set; }

    public Nullable<int> ConceptID { get; set; }

    public Nullable<int> NumberArtical { get; set; }

    public string KeyNorm { get; set; }

    public Nullable<int> LawID { get; set; }

}

}
