
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class KeyRelate: ICloneable
{
	public KeyRelate () {}

	#region ICloneable Members
    public KeyRelate Clone()
    {
        return (KeyRelate)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (KeyRelate)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public int KeyPhraseID1 { get; set; }

    public int KeyPhraseID2 { get; set; }

    public Nullable<int> NumArtical { get; set; }

    public Nullable<int> NumCount { get; set; }

    public Nullable<int> LawID { get; set; }

}

}
