
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class M_COMMON: ICloneable
{
	public M_COMMON () {}

	#region ICloneable Members
    public M_COMMON Clone()
    {
        return (M_COMMON)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (M_COMMON)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string Name { get; set; }

    public Nullable<byte> Type { get; set; }

    public Nullable<int> OrderIndex { get; set; }

    public Nullable<bool> DelFlg { get; set; }

    public Nullable<System.DateTime> CreateAt { get; set; }

    public Nullable<System.DateTime> UpdateAt { get; set; }

    public string Unit { get; set; }

}

}
