
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class query: ICloneable
{
	public query () {}

	#region ICloneable Members
    public query Clone()
    {
        return (query)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (query)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string value { get; set; }

    public string result { get; set; }

    public Nullable<System.DateTime> Datetime { get; set; }

    public Nullable<int> UserID { get; set; }

}

}
