
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class QuestionContain: ICloneable
{
	public QuestionContain () {}

	#region ICloneable Members
    public QuestionContain Clone()
    {
        return (QuestionContain)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (QuestionContain)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string Contain { get; set; }

    public Nullable<int> QuestionTypeID { get; set; }

}

}
