
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VNPTPM.Model
{

using System;
    using System.Collections.Generic;
    
[Serializable]
public partial class Settings: ICloneable
{
	public Settings () {}

	#region ICloneable Members
    public Settings Clone()
    {
        return (Settings)this.MemberwiseClone(); 
    }

    object ICloneable.Clone()
    {
        return (Settings)this.MemberwiseClone();
    }
    #endregion

    public int ID { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

}

}
